name: 11serp_Scan

on:
  schedule:
    - cron: '03 * * * *'  #run 
  workflow_dispatch:  # Allows manual run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'
    - name: Check if SERPAPI_KEY is set
      run: |
        if [ -z "${{ secrets.SERPAPI_KEY }}" ]; then
          echo "SERPAPI_KEY is not set!"
          exit 1
        else
          echo "SERPAPI_KEY is set!"
        fi

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run python script 11
      env:
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BNBSCAN_API_KEY: ${{ secrets.BNBSCAN_API_KEY }}
        CHAINBASE_API: ${{ secrets.CHAINBASE_API }}
        WEB3_RPC: ${{ secrets.WEB3_RPC }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        NETWORK: ${{ secrets.NETWORK }}
        MAINFILE: ${{ secrets.MAINFILE }}
        DUNE_QUERY: ${{ secrets.DUNE_QUERY }}
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        CHAINBASE_API_URL: ${{ secrets.CHAINBASE_API_URL }}
        BNBSCAN_BASE_URL: ${{ secrets.BNBSCAN_BASE_URL }}
      run: python 11findSitesFromSerp.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git config pull.rebase false
        git pull
        git add -A
        git diff --cached --exit-code || git commit -m "Automated update from GitHub Actions ($GITHUB_WORKFLOW)"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to commit"

    - name: Run python script 11
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      run: python 11findSitesFromSerp.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git config pull.rebase false
        git pull
        git add -A
        git diff --cached --exit-code || git commit -m "Automated update from GitHub Actions ($GITHUB_WORKFLOW)"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to commit"



