name: 11serp_Scan

on:
  schedule:
    - cron: '05 * * * *'  #run 
  workflow_dispatch:  # Allows manual run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check if SERPAPI_KEY is set
      run: |
        if [ -z "${{ secrets.SERPAPI_KEY }}" ]; then
          echo "SERPAPI_KEY is not set!"
          exit 1
        else
          echo "SERPAPI_KEY is set!"
        fi

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Run python script 11
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      run: python 11findSitesFromSerp.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git diff --cached --exit-code || git commit -m "Automated update from GitHub Actions ($GITHUB_WORKFLOW)"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to commit"


