name: 12trackCoingGlassRSI

on:
  schedule:
    - cron: '*/15 6-15 * * *'  # Run every 15 minutes from 6 to 15 UTC
  workflow_dispatch:  # Allows manual run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'
    - name: Check if OPENAI_API_KEY is set
      run: |
        if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
          echo "OPENAI_API_KEY is not set!"
          exit 1
        else
          echo "OPENAI_API_KEY is set!"
        fi
    - name: Install XVFB and other libs
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb unrar p7zip-full
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: playwright install chromium   

    - name: Run python script 12trackCoingGlassRSI
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BNBSCAN_API_KEY: ${{ secrets.BNBSCAN_API_KEY }}
        CHAINBASE_API: ${{ secrets.CHAINBASE_API }}
        WEB3_RPC: ${{ vars.WEB3_RPC }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        NETWORK: ${{ vars.NETWORK }}
        MAINFILE: ${{ vars.MAINFILE }}
        DUNE_QUERY: ${{ secrets.DUNE_QUERY }}
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        CHAINBASE_API_URL: ${{ vars.CHAINBASE_API_URL }}
        ETHSCAN_BASE_URL: ${{ vars.ETHSCAN_BASE_URL }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: xvfb-run python 12trackCoingGlassRSI.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git config pull.rebase false
        git add -A
        git diff --cached --exit-code || git commit -m "Automated update from GitHub Actions ($GITHUB_WORKFLOW)"
        git pull
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to commit"
