name: Search Bnb20 tokens and scan source for sites

on:
  schedule:
    - cron: '0 */2 * * *' # 
  workflow_dispatch:  # Allows manual run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run searchErcFromLastTransfers3.py
      env:
        BNBSCAN_API_KEY: ${{ secrets.BNBSCAN_API_KEY }}
        CHAINBASE_API: ${{ secrets.CHAINBASE_API }}
        WEB3_RPC: ${{ secrets.WEB3_RPC }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        NETWORK: ${{ env.NETWORK }}
        MAINFILE: ${{ env.MAINFILE }}
        DUNE_QUERY: ${{ secrets.DUNE_QUERY }}
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        DUNE_API_KEY2: ${{ secrets.DUNE_API_KEY2 }}
        CHAINBASE_API_URL: ${{ env.CHAINBASE_API_URL }}
        ETHSCAN_BASE_URL: ${{ env.ETHSCAN_BASE_URL }}
      run: python 4searchErcFromLastTransfers3.py
 
    - name: Run ScanBnberc20.py
      env:
        BNBSCAN_API_KEY: ${{ secrets.BNBSCAN_API_KEY }}
        CHAINBASE_API: ${{ secrets.CHAINBASE_API }}
        WEB3_RPC: ${{ secrets.WEB3_RPC }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        NETWORK: ${{ env.NETWORK }}
        MAINFILE: ${{ env.MAINFILE }}
        DUNE_QUERY: ${{ secrets.DUNE_QUERY }}
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        CHAINBASE_API_URL: ${{ env.CHAINBASE_API_URL }}
        ETHSCAN_BASE_URL: ${{ env.ETHSCAN_BASE_URL }}
      run: python 4ScanBnberc20.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git diff --cached --exit-code || git commit -m "Automated update from GitHub Actions ($GITHUB_WORKFLOW)"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to commit"
